display_errors = On
display_startup_errors = On
upload_max_filesize = 200M
post_max_size = 200M
short_open_tag = Off
memory_limit =  1G
max_execution_time = 3600

date.timezone = Europe/Brussels
intl.default_locale=nl_BE

sendmail_path = /usr/bin/env catchmail -f dev@bart.be

;xdebug.mode=off
xdebug.mode=debug,develop
xdebug.idekey=PHPSTORM
xdebug.start_with_request=yes
xdebug.discover_client_host=false
xdebug.client_host=172.29.0.1
xdebug.client_port=9003
xdebug.log=/var/www/log/xdebug.log
xdebug.show_error_trace=1
xdebug.max_nesting_level=512
